# Ultimate Shopify Theme Check Configuration
# 100% Theme Store Compliance & Production Ready
# Generated for Shopify CLI v3.84.2 with complete validation coverage
# Documentation: https://shopify.dev/docs/themes/tools/theme-check

# Root directory for theme files - point to code library
root: "shopify-liquid-guides/code-library"

# Use comprehensive validation preset as base
extends:
  - "theme-check:all"

# Files/directories to exclude from checking
ignore:
  - "node_modules/**"
  - "dist/**"
  - "build/**"
  - "_archive/**"
  - ".git/**"
  - ".claude/**"
  - ".vscode/**"
  - "shopify-liquid-guides/examples/*.json"  # Documentation examples
  - "shopify-liquid-guides/docs/**/*.md"     # Markdown docs
  - "shopify-liquid-guides/docs/layouts/**/*.liquid"  # Example layouts

# ===================================================================
# CRITICAL ERROR LEVEL CHECKS - Theme Store Blockers
# Updated to align with enhanced validator architecture (2025)
# ===================================================================

# NEW: App Block Validation (Theme Store Critical)
AppBlockMissingSchema:
  enabled: true
  severity: error

AppBlockValidTags:
  enabled: true
  severity: error

# NEW: Required Layout Objects
RequiredLayoutThemeObject:
  enabled: true
  severity: error

# Syntax and Structure
JSONSyntaxError:
  enabled: true
  severity: error

LiquidHTMLSyntaxError:
  enabled: true
  severity: error

ValidSchema:
  enabled: true
  severity: error

UnknownFilter:
  enabled: true
  severity: error

# Schema Validation (CRITICAL for Theme Store)
ValidSchemaName:
  enabled: true
  severity: error

ValidSettingsKey:
  enabled: true
  severity: error

ValidLocalBlocks:
  enabled: true
  severity: error

ValidBlockTarget:
  enabled: true
  severity: error

ValidStaticBlockType:
  enabled: true
  severity: error

ValidVisibleIf:
  enabled: true
  severity: error

# Content and Arguments Validation
ValidContentForArguments:
  enabled: true
  severity: error

ValidContentForArgumentTypes:
  enabled: true
  severity: warning

ValidRenderSnippetArgumentTypes:
  enabled: true
  severity: warning

# JSON Template Validation
JSONMissingBlock:
  enabled: true
  severity: error

# Unique Identifiers
UniqueSettingId:
  enabled: true
  severity: error

UniqueStaticBlockId:
  enabled: true
  severity: error

UniqueDocParamNames:
  enabled: true
  severity: error

# Block and Static Content
CaptureOnContentForBlock:
  enabled: true
  severity: error

SchemaPresetsStaticBlocks:
  enabled: true
  severity: error

StaticStylesheetAndJavascriptTags:
  enabled: true
  severity: error

# Documentation Validation
ValidDocParamTypes:
  enabled: true
  severity: error

ReservedDocParamNames:
  enabled: true
  severity: error

UnsupportedDocTag:
  enabled: true
  severity: error

# ===================================================================
# WARNING LEVEL CHECKS - Best Practices & Performance
# Enhanced with new validation rules from our architecture improvements
# ===================================================================

# NEW: Asset Size Validation
AssetSizeCSS:
  enabled: true
  severity: warning
  max_size: 100000  # 100KB limit

AssetSizeJavaScript:
  enabled: true
  severity: warning

AssetSizeAppBlockCSS:
  enabled: true
  severity: error
  max_size: 100000  # 100KB limit for app blocks

AssetSizeAppBlockJavaScript:
  enabled: true
  severity: error
  max_size: 10000  # 10KB limit for app blocks

# NEW: Enhanced Performance Checks
ParserBlockingJavaScript:
  enabled: true
  severity: error

# Settings and Schema Best Practices
LiquidFreeSettings:
  enabled: true
  severity: warning

SchemaPresetsBlockOrder:
  enabled: true
  severity: warning

EmptyBlockContent:
  enabled: true
  severity: warning

# Performance Optimization
PaginationSize:
  enabled: true
  severity: warning
  min_size: 1
  max_size: 50

AssetPreload:
  enabled: true
  severity: warning

RemoteAsset:
  enabled: true
  severity: info

ImgWidthAndHeight:
  enabled: true
  severity: error

# Deprecated Patterns
DeprecatedFilter:
  enabled: true
  severity: warning

DeprecatedTag:
  enabled: true
  severity: warning

DeprecateLazysizes:
  enabled: true
  severity: warning

DeprecateBgsizes:
  enabled: true
  severity: warning

DeprecatedFontsOnSectionsAndBlocks:
  enabled: true
  severity: warning

DeprecatedFontsOnSettingsSchema:
  enabled: true
  severity: warning

# Code Quality
VariableName:
  enabled: true
  severity: warning
  format: snake_case

HardcodedRoutes:
  enabled: true
  severity: warning

UnclosedHTMLElement:
  enabled: true
  severity: warning

# Argument Validation
MissingContentForArguments:
  enabled: true
  severity: warning

MissingRenderSnippetArguments:
  enabled: true
  severity: warning

DuplicateContentForArguments:
  enabled: true
  severity: warning

DuplicateRenderSnippetArguments:
  enabled: true
  severity: warning

UnrecognizedContentForArguments:
  enabled: true
  severity: warning

UnrecognizedRenderSnippetArguments:
  enabled: true
  severity: warning

UnusedDocParam:
  enabled: true
  severity: warning

# ===================================================================
# SECURITY CHECKS - Critical for Production
# ===================================================================

ContentForHeaderModification:
  enabled: true
  severity: error

CdnPreconnect:
  enabled: true
  severity: error

# ===================================================================
# INFORMATION LEVEL CHECKS - Development Guidance
# ===================================================================

ParserBlockingScript:
  enabled: true
  severity: info

ValidHTMLTranslation:
  enabled: true
  severity: warning

ValidJSON:
  enabled: true
  severity: info

BlockIdUsage:
  enabled: true
  severity: warning

# ===================================================================
# MISSING ASSETS - Critical for Theme Functionality
# ===================================================================

MissingAsset:
  enabled: true
  severity: error

# ===================================================================
# DOCUMENTATION REPOSITORY SPECIFIC ADJUSTMENTS
# ===================================================================

# Note: Some checks are intentionally configured for documentation use
# These settings optimize for educational examples while maintaining quality

# For production themes, consider enabling these:
# UnusedAssign: true (disabled here for educational examples)
# UnusedSnippet: true (disabled here for snippet library)
# MissingRequiredTemplateFiles: true (disabled for documentation)